# Copyright 2012 cosmo
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by cosmo

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal git-2
DESCRIPTION="The base package for Fay. This package exports Prelude and FFI which you probably want to use with Fay."
HOMEPAGE="https://github.com/faylang/fay-base"
SRC_URI=""
EGIT_REPO_URI="git://github.com/faylang/fay-base.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/fay-0.12:=[profile?]
		>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
